### ISSUE TITLE
Login Endpoint

### ISSUE THREAD

**Issue by PrajeetShrestha** [hyperoslo/hyper-recipes#12]
Hi,
There is a API for user registration but I  don't see any end point for user login. :)
Thanks :)

**Comment by 3lvis** [comment]
Hi @PrajeetShrestha maybe this is not well explained in the README, but when it says "User registration" it really means applicant registration, so it creates an endpoint for the usage of the applicant.

Hyper Recipes doesn't have "users" and authentication per se as we are trying to keep it simple.

Let me know if this helps :)

**Comment by PrajeetShrestha** [comment]
So will the access token be a constant for a same email address?

**Comment by 3lvis** [comment]
@PrajeetShrestha Yes, the token is your token, your way to get access to the HTTP endpoints.

**Comment by PrajeetShrestha** [comment]
Oh okay. I thought that access token has a expiry and prone to change. Thank you for clarification.
