### ISSUE TITLE
Spec and test directories

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/hyper-recipes#16]
Are we using RSpec, MiniTest or Test::Unit on this project?

**Comment by sindrenm** [comment]
What is “*Test” supposed to mean? MiniTest or Test::Unit? :stuck_out_tongue_winking_eye:

**Comment by timkurvers** [comment]
Ah, sorry I thought the thing was called UnitTest. Will edit.

**Comment by sindrenm** [comment]
:ghost: :foggy:

**Comment by sindrenm** [comment]
:trollface:
