### ISSUE TITLE
Isolate the data set

### ISSUE THREAD

**Issue by jgorset** [hyperoslo/hyper-recipes#2]
A lot of applicants use this API in their applications, which means that things could randomly change. One applicant might delete all of the recipes, for example, and somewhere else in the world another might wonder why his application suddenly "stopped working".

It would be pretty neat if applicants could work on their own isolated data set somehow. We might accomplish that with a prefix to the path (like `hyper-recipes.herokuapp.com/jgorset/recipes`), or perhaps a header of some sort (like `X-Namespace: jgorset`) — or maybe something else entirely!

**Comment by ohenrik** [comment]
Cool idea. So is it possible to "lock" the data on the top level domain as a "read only" and allow alterations on any other subdomain by for example creating a copy of the original data when a user first visits a certain subdomain? That is every new subdomain that is visited gets its own copy of the data.

**Comment by sindrenm** [comment]
> A lot of applicants use this API in their applications

Yah.

**Comment by sindrenm** [comment]
> A lot of applicants use this API in their applications

Haha, I read “a lot of applications use this API” for some reason. :stuck_out_tongue_closed_eyes:

**Comment by sindrenm** [comment]
Or you could have some user account system and that your user have access to your own (and only your own) recipes. And then we just set up a new user per applicant, which would be done by us, I suppose.

**Comment by jgorset** [comment]
@ohenrik: _That's_ a cool idea! I initially thought we'd just have seeds and initialize the new data sets from that, but that's next level!

**Comment by jgorset** [comment]
@sindrenm: Yeah, but I think as long as it's something that isn't listed anywhere you can be reasonably sure that nobody will tamper with your recipes anyway. Also then it's less trouble to get started.

**Comment by sindrenm** [comment]
Yeah, you're probably right. :smiley:

**Comment by 3lvis** [comment]
This would be wonderful, wonderful.

**Comment by timkurvers** [comment]
I like @jgorset's sub-path idea :+1:
