### ISSUE TITLE
Check access rights for recipe 14

### ISSUE THREAD

**Issue by ealmdahl** [hyperoslo/hyper-recipes#4]
The images for recipe 14
[full](https://hyper-recipes.s3.amazonaws.com/uploads/recipe/photo/14/peach+cobbler+4.jpg)
[thumb](https://hyper-recipes.s3.amazonaws.com/uploads/recipe/photo/14/thumbnail_peach+cobbler+4.jpg)
give Access Denied error. Please fix :)

**Comment by 3lvis** [comment]
I think it's related to having `+` in the name of the file.

**Comment by 3lvis** [comment]
https://github.com/hyperoslo/hyper-recipes/pull/5

**Comment by ealmdahl** [comment]
sweet! can you push it to heroku as well?

**Comment by 3lvis** [comment]
@ealmdahl The seeds need to be re-run for this to work.

**Comment by 3lvis** [comment]
Found the deploy command in Heroku.com!

![screen shot 2015-03-12 at 09 33 59](https://cloud.githubusercontent.com/assets/1088217/6614480/f706ab9e-c89a-11e4-9f57-c55d857dd9c9.png)

**Comment by 3lvis** [comment]
@ealmdahl Fixed http://hyper-recipes.herokuapp.com/recipes.json

**Comment by sindrenm** [comment]
@NSElvis: That deploy from Heroku is really sweet, just beware when you have migrations in your app, as they won't be automatically run. :smiley:

**Comment by 3lvis** [comment]
@sindrenm Super smart of them to add GitHub integration.

**Comment by ealmdahl** [comment]
This is good. Thanks, @NSElvis :+1:
