### ISSUE TITLE
Normalize string literal quoting

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/hyper-recipes#7]
According to Ruby style guide: https://github.com/bbatsov/ruby-style-guide#strings

**Comment by sindrenm** [comment]
:+1:

**Comment by jgorset** [comment]
Where doesn't it do this? I can only find nicely interpolated strings.

**Comment by timkurvers** [comment]
Will post a couple of instances soon.

**Comment by jgorset** [comment]
Cool – might as well just fix them and make a pull request while you're at it. ;-)
