### ISSUE TITLE
The user creation not working!

### ISSUE THREAD

**Issue by PrajeetShrestha** [hyperoslo/hyper-recipes#8]
Hi,
The user creation API http://hyper-recipes.herokuapp.com is still not working.

**Comment by 3lvis** [comment]
Hi @PrajeetShrestha, sorry for breaking it without warning. We are working on get it up and running again.

**Comment by PrajeetShrestha** [comment]
Ok will be waiting for it thanx :)

**Comment by 3lvis** [comment]
@PrajeetShrestha Creating work users should work now, please let us know otherwise.

Again, sorry for just breaking it with no :warning:!

Have a nice day. 

:star2:  :cake:  :star2:

**Comment by PrajeetShrestha** [comment]
Hi, Sorry to bother but I don't think it's still working.

**Comment by 3lvis** [comment]
@PrajeetShrestha Will look into it :)

**Comment by jgorset** [comment]
Hi @PrajeetShrestha! I'm having a hard time reproducing this – what seems to be going wrong for you?

```
$ curl -d "user[email]=johannes@hyper.no" -d "user[password]=password" -d "user[password_confirmation]=password" http://hyper-recipes.herokuapp.com/users
{"id":13,"email":"johannes@hyper.no","password_digest":"$2a$10$ON71CpPCKOeSn4vqQaUMpO9kUwlzSGcgOemp3Ix1.EWjYCgZ.muQK","auth_token":"34703e07c3f45d9f8438","created_at":"2015-05-01T06:22:27.917Z","updated_at":"2015-05-01T06:22:27.917Z","seed_recipes":false}                                                                                                        

$ curl -d "user[email]=johannes@hyper.no" -d "user[password]=password" -d "user[password_confirmation]=password" -d "user[seed_recipes]=true" http://hyper-recipes.herokuapp.com/users
{"id":14,"email":"johannes@hyper.no","password_digest":"$2a$10$9mQIy7c/fo/.TqPDBx6j2OrhOodVFU.zYPu3aD1cAPj82blwDlPP6","auth_token":"3c472356a39632422d7e","created_at":"2015-05-01T06:23:10.076Z","updated_at":"2015-05-01T06:23:10.076Z","seed_recipes":true}
```

**Comment by PrajeetShrestha** [comment]
Hi, 
At last figured it out. :) The end point in the documentation (https://github.com/hyperoslo/hyper-recipes) seem to be incorrect. :)  It's "POST: /user" there. Should be "POST: /users" . Didn't noticed the URL in the curl script.

Thanx for the kind help :).

**Comment by 3lvis** [comment]
@PrajeetShrestha don't worry! Hope you're having fun.

**Comment by jgorset** [comment]
Ohhh, sorry about that! I didn't see it either. Thanks for fixing, @t0ggah.
